### ISSUE TITLE
Why ES256 ? afaik it is not supported in Kubernetes

### ISSUE THREAD

**Issue by victorgp** [kismatic/kubernetes-ldap#14]
Why using ES256 for the key generation? I think it is not supported in Kubernetes, does it work for you? if so, what version of Kubernetes are you using?

I'm getting: "Unable to authenticate the request due to an error: signing method (alg) is unavailable."

Which means that this algorithm is not registered in Kubernetes

**Comment by victorgp** [comment]
Kubernetes uses jwt-go from github.com/dgrijalva/jwt-go and ecdsa was added to that repo on Sep 17, 2015 (https://github.com/dgrijalva/jwt-go/commit/bf3befad727d550999cab570c1cd3db681a732f6) but the version Kubernetes is using is from Apr 20, 2015 as you can see in GoDeps https://github.com/kubernetes/kubernetes/blob/master/Godeps/Godeps.json

Even for current master branch, so i think this cannot work with Kubernetes.

Is this actually working for you?

**Comment by alexbrand** [comment]
The ES256 key is used for signing and verifying tokens issued by the webhook. Kuberenetes is not involved in this. It simply issues requests to the webhook when authenticating users that supply a token.

Can you share some more detail on how you setup the authentication plugin? What version of Kubernetes are you using?

**Comment by victorgp** [comment]
Sure, i'm using v1.2

For the api server i'm using this webhook config file

```
# clusters refers to the remote service.
clusters:
  - name: ldap-auth-webhook
    cluster:
      certificate-authority: ca.pem      # CA for verifying the remote service.
      server: https://k8s-ldap-auth.stg.dc1.thousandeyes.com:4000/authenticate # URL of remote service to query. Must use 'https'.

# users refers to the API Server's webhook configuration.
users:
  - name: ldap-auth-webhook-client
    user:
      client-certificate: client-user.pem # cert for the webhook plugin to use
      client-key: client-user-key.pem          # key matching the cert

# kubeconfig files require a context. Provide one for the API Server.
current-context: webhook
contexts:
- context:
    cluster: ldap-auth-webhook
    user: ldap-auth-webhook-client
  name: webhook
```

The only difference from what you mention in the documentation are the parameters i set to the api server, you mention authentication-token-webhook-cache-ttl and authentication-token-webhook-config-file but those don't exist yet in stable version (v1.2) maybe they exist in alpha version (v1.3).

In stable version the ones that exist are:
```
--authorization-mode=Webhook
--authorization-webhook-config-file=/etc/kubernetes/webhook-config/webhook-config.yaml
```

Which are the ones i set. From the [documentation](http://kubernetes.io/docs/admin/authorization/) i understand the logic is the same and it should work, the api server makes a request to https://k8s-ldap-auth.stg.dc1.thousandeyes.com:4000/authenticate with a specific JSON describing the type of request.

The problem here is that no request is arriving to the kubernetes-ldap service in /authenticate end point, i've modified the code to debug it and there are no requests from the api.

Then in the api logs, i get: "Unable to authenticate the request due to an error: signing method (alg) is unavailable." so the api server seems to be doing something in between with that token.
